server:
  port: 8004
spring:
  application:
    name: es-producto
  datasource:
    url: jdbc:postgresql://10.35.3.251:5432/facturacion_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver