server:
  port: 8004
spring:
  cloud:
    config:
      profile: dev
  application:
    name: prueba
  datasource:
    url: jdbc:postgresql://10.35.3.251:5432/facturacion_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver